# Generated by Django 5.2.7 on 2025-10-27 23:32

import django.db.models.deletion
import tt.apps.attribute.enums
import tt.apps.bookings.enums
import tt.apps.common.model_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("itineraries", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_status",
                    tt.apps.common.model_fields.LabeledEnumField(
                        choices=[
                            ("todo", "To-do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        enum_class=tt.apps.bookings.enums.BookingStatus,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "payment_status",
                    tt.apps.common.model_fields.LabeledEnumField(
                        choices=[
                            ("no", "No"),
                            ("partial", "Partial"),
                            ("autopay", "Auto-pay"),
                            ("yes", "Yes"),
                        ],
                        default="no",
                        enum_class=tt.apps.bookings.enums.PaymentStatus,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Payment Status",
                    ),
                ),
                ("cancellation_policy", models.TextField(blank=True)),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmed?"),
                ),
                ("booking_site", models.CharField(blank=True, max_length=200)),
                ("booking_reference", models.CharField(blank=True, max_length=200)),
                ("confirmation_number", models.CharField(blank=True, max_length=200)),
                ("payment_method", models.CharField(blank=True, max_length=100)),
                ("booking_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, help_text="E.g., USD, EUR, GBP", max_length=3
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "itinerary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="itineraries.itineraryitem",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Data",
                "verbose_name_plural": "Booking Data",
            },
        ),
        migrations.CreateModel(
            name="BookingAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "file_value",
                    models.FileField(blank=True, null=True, upload_to="attributes/"),
                ),
                (
                    "file_mime_type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Mime Type"
                    ),
                ),
                (
                    "value_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("secret", "Secret"),
                            ("enum", "Enum"),
                            ("boolean", "Boolean"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                        ],
                        default="text",
                        enum_class=tt.apps.attribute.enums.AttributeValueType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "value_range_str",
                    models.TextField(blank=True, null=True, verbose_name="Value Range"),
                ),
                (
                    "attribute_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        choices=[("predefined", "Predefined"), ("custom", "Custom")],
                        default="predefined",
                        enum_class=tt.apps.attribute.enums.AttributeType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Attribute Type",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "booking_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="bookings.bookingdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Attribute",
                "verbose_name_plural": "Booking Attributes",
            },
        ),
    ]
