# Generated by Django 5.2.7 on 2025-11-20 17:04

import django.db.models.deletion
import tt.apps.attribute.enums
import tt.apps.common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "rating",
                    models.IntegerField(blank=True, help_text="Rating", null=True),
                ),
                (
                    "posted_to",
                    models.CharField(
                        blank=True, help_text="Delimited list of sites", max_length=500
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="locations.location",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "file_value",
                    models.FileField(blank=True, null=True, upload_to="attributes/"),
                ),
                (
                    "file_mime_type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Mime Type"
                    ),
                ),
                (
                    "value_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="text",
                        enum_class=tt.apps.attribute.enums.AttributeValueType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "value_range_str",
                    models.TextField(blank=True, null=True, verbose_name="Value Range"),
                ),
                (
                    "attribute_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="predefined",
                        enum_class=tt.apps.attribute.enums.AttributeType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Attribute Type",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Attribute",
                "verbose_name_plural": "Review Attributes",
            },
        ),
    ]
