TIMEZONE_NAME_LIST = [
    'UTC',
    'America/New_York',
    'America/Chicago',
    'America/Denver',
    'America/Los_Angeles',
    'America/Toronto',
    'America/Mexico_City',
    'America/Sao_Paulo',
    'Europe/London',
    'Europe/Berlin',
    'Europe/Paris',
    'Europe/Moscow',
    'Asia/Dubai',
    'Asia/Tokyo',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Hong_Kong',
    'Asia/Singapore',
    'Asia/Kolkata',
    'Asia/Jakarta',
    'Australia/Sydney',
    'Australia/Melbourne',
    'Africa/Johannesburg',
    'Africa/Lagos',
    'Africa/Cairo',
    'America/Argentina/Buenos_Aires',
]

    
# HTML div ids (classes and attributes) that app logic depends on.
DIVID = {
    # Attribute Editing
    'ATTR_V2_CONTAINER_ID': 'attr-v2-container',
    'ATTR_V2_CONTAINER_CLASS': 'attr-v2-container',
    'ATTR_V2_FORM_ID': 'attr-v2-form',
    'ATTR_V2_FORM_CLASS': 'attr-v2-form',
    'ATTR_V2_CONTENT_ID': 'attr-v2-content',
    'ATTR_V2_CONTENT_CLASS': 'attr-v2-content',
    'ATTR_V2_UPLOAD_FORM_CONTAINER_ID': 'attr-v2-upload-form-container',
    'ATTR_V2_FILE_GRID_ID': 'attr-v2-file-grid',
    'ATTR_V2_FILE_GRID_CLASS': 'attr-v2-file-grid',
    'ATTR_V2_STATUS_MESSAGE_ID': 'attr-v2-status-message',
    'ATTR_V2_STATUS_MESSAGE_CLASS': 'attr-v2-status-message',
    'ATTR_V2_DIRTY_MESSAGE_ID': 'attr-v2-dirty-message',
    'ATTR_V2_DIRTY_MESSAGE_CLASS': 'attr-v2-dirty-message',
    'ATTR_V2_UPDATE_BTN_ID': 'attr-v2-update-btn',
    'ATTR_V2_UPDATE_BTN_CLASS': 'attr-v2-update-btn',
    'ATTR_V2_ATTRIBUTE_CARD_CLASS': 'attr-v2-attribute-card',
    'ATTR_V2_NEW_ATTRIBUTE_CLASS': 'attr-v2-new-attribute',
    'ATTR_V2_FILE_TITLE_INPUT_CLASS': 'attr-v2-file-title-input',
    'ATTR_V2_FILE_INFO_CLASS': 'attr-v2-file-info',
    'ATTR_V2_ATTRIBUTE_NAME_CLASS': 'attr-v2-attribute-name',
    'ATTR_V2_DELETE_BTN_CLASS': 'attr-v2-delete-btn',
    'ATTR_V2_UNDO_BTN_CLASS': 'attr-v2-undo-btn',
    'ATTR_V2_FILE_CARD_CLASS': 'attr-v2-file-card',
    'ATTR_V2_FILE_NAME_CLASS': 'attr-v2-file-filename',
    'ATTR_V2_SECRET_INPUT_WRAPPER_CLASS': 'attr-v2-secret-input-wrapper',
    'ATTR_V2_SECRET_INPUT_CLASS': 'attr-v2-secret-input',
    'ATTR_V2_ICON_SHOW_CLASS': 'attr-v2-icon-show',
    'ATTR_V2_ICON_HIDE_CLASS': 'attr-v2-icon-hide',
    'ATTR_V2_TEXTAREA_CLASS': 'attr-v2-textarea',
    'ATTR_V2_TEXT_VALUE_WRAPPER_CLASS': 'attr-v2-text-value-wrapper',
    'ATTR_V2_EXPAND_CONTROLS_CLASS': 'attr-v2-expand-controls',
    'ATTR_V2_FILE_INPUT_ID': 'attr-v2-file-input',
    'ATTR_V2_FILE_INPUT_CLASS': 'attr-v2-file-input',
    'ATTR_V2_ADD_ATTRIBUTE_BTN_ID': 'attr-v2-add-attribute-btn',
    'ATTR_V2_SCROLLABLE_CONTENT_ID': 'attr-v2-scrollable-content',
    'ATTR_V2_SCROLLABLE_CONTENT_CLASS': 'attr-v2-scrollable-content',
    'ATTR_V2_AUTO_DISMISS_CLASS': 'attr-v2-auto-dismiss',
    'ATTR_V2_HISTORY_LINK_CLASS': 'attr-v2-history-link',
    'ATTR_V2_RESTORE_LINK_CLASS': 'attr-v2-restore-link',
    'ATTR_V2_STICKY_PANEL_CLASS': 'attr-v2-sticky-panel',
    'ATTR_V2_ACTION_BAR_CLASS': 'attr-v2-action-bar',
    'ATTR_V2_ACTION_BAR_CONTENT_CLASS': 'attr-v2-action-bar-content',
    'ATTR_V2_ACTION_BUTTONS_CLASS': 'attr-v2-action-buttons',
    'ATTR_V2_HISTORY_INLINE_CONTENT_CLASS': 'attr-v2-history-inline-content',
    'ATTR_V2_HISTORY_HEADER_CLASS': 'attr-v2-history-header',
    'ATTR_V2_HISTORY_CLOSE_CLASS': 'attr-v2-history-close',
    'ATTR_V2_HISTORY_CURRENT_CLASS': 'attr-v2-history-current',
    'ATTR_V2_HISTORY_RECORDS_CLASS': 'attr-v2-history-records',
    'ATTR_V2_HISTORY_RECORD_CLASS': 'attr-v2-history-record',
    'ATTR_V2_HISTORY_TOGGLE_CLASS': 'attr-v2-history-toggle',
    'ATTR_V2_HISTORY_EMPTY_CLASS': 'attr-v2-history-empty',
    'ATTR_V2_ATTRIBUTE_HEADER_CLASS': 'attr-v2-attribute-header',
    'ATTR_V2_ATTRIBUTE_ACTIONS_CLASS': 'attr-v2-attribute-actions',
    'ATTR_V2_ATTRIBUTE_VALUE_CLASS': 'attr-v2-attribute-value',
    'ATTR_V2_FORM_DISPLAY_LABEL_CLASS': 'attr-v2-form-display-label',
    'ATTR_V2_TEXT_VALUE_CLASS': 'attr-v2-text-value',
    'ATTR_V2_SECRET_CHECKBOX_CLASS': 'attr-v2-secret-checkbox',
    'ATTR_V2_INLINE_HISTORY_CLASS': 'attr-v2-inline-history',
    'ATTR_V2_DISPLAY_FIELD_CLASS': 'display-field',
    'ATTR_V2_SHOW_MORE_TEXT_CLASS': 'show-more-text',
    'ATTR_V2_SHOW_LESS_TEXT_CLASS': 'show-less-text',
    'ATTR_V2_DELETE_FILE_ATTR': 'delete_file_attribute',

    # Trip Images Upload
    'IMAGES_UPLOAD_ZONE_ID': 'images-upload-zone',
    'IMAGES_FILE_INPUT_ID': 'images-file-input',
    'IMAGES_PROGRESS_SECTION_ID': 'images-progress-section',
    'IMAGES_PROGRESS_COUNT_ID': 'images-progress-count',
    'IMAGES_FILE_PROGRESS_LIST_ID': 'images-file-progress-list',
    'IMAGES_UPLOADED_GRID_ID': 'images-uploaded-grid',
    'IMAGES_UPLOADED_COUNT_ID': 'images-uploaded-count',
}
