# Generated by Django 5.2.7 on 2025-10-27 23:30

import django.db.models.deletion
import tt.apps.common.model_fields
import tt.apps.trips.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trip_status",
                    tt.apps.common.model_fields.LabeledEnumField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("current", "Current"),
                            ("past", "Past"),
                        ],
                        default="upcoming",
                        enum_class=tt.apps.trips.enums.TripStatus,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Trip Status",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["-created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_datetime"],
                        name="trips_trip_user_id_ec42e7_idx",
                    )
                ],
            },
        ),
    ]
