# Generated by Django 5.2.7 on 2025-11-02 00:28

import django.db.models.deletion
import tt.apps.common.model_fields
import tt.apps.trips.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trip_status",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="upcoming",
                        enum_class=tt.apps.trips.enums.TripStatus,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Trip Status",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="TripMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="owner",
                        enum_class=tt.apps.trips.enums.TripPermissionLevel,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Permission Level",
                    ),
                ),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Member",
                "verbose_name_plural": "Trip Members",
                "indexes": [
                    models.Index(
                        fields=["user", "trip"], name="trips_tripm_user_id_aee072_idx"
                    ),
                    models.Index(
                        fields=["trip", "permission_level"],
                        name="trips_tripm_trip_id_e1162e_idx",
                    ),
                ],
                "unique_together": {("trip", "user")},
            },
        ),
    ]
