# Generated by Django 5.2.7 on 2025-11-23 18:30

import tt.apps.common.model_fields
import tt.apps.trips.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trip_status",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="upcoming",
                        enum_class=tt.apps.trips.enums.TripStatus,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Trip Status",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["-created_datetime"],
            },
        ),
    ]
