# Generated by Django 5.2.7 on 2025-11-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmember",
            name="invitation_accepted_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invitation was accepted. Used for one-time token validation.",
                null=True,
            ),
        ),
    ]
