# Generated by Django 5.2.7 on 2025-12-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_add_reference_image_to_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
