# Generated by Django 5.2.7 on 2025-12-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_add_version_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="gmm_map_id",
            field=models.CharField(
                blank=True,
                help_text="Google My Maps map identifier (from URL mid parameter)",
                max_length=255,
                null=True,
            ),
        ),
    ]
