# Generated by Django 5.2.7 on 2025-12-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_add_gmm_map_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="gmm_map_id",
            field=models.CharField(
                blank=True,
                help_text="Google My Maps map identifier (from URL mid parameter)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
