# Generated by Django 5.2.7 on 2025-11-20 17:17

import django.db.models.deletion
import tt.apps.common.model_fields
import tt.apps.trips.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="owner",
                        enum_class=tt.apps.trips.enums.TripPermissionLevel,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Permission Level",
                    ),
                ),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation_accepted_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted. Used for one-time token validation.",
                        null=True,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Member",
                "verbose_name_plural": "Trip Members",
                "unique_together": {("trip", "user")},
            },
        ),
    ]
