# Generated by Django 5.2.7 on 2025-12-07 17:26

import tt.apps.api.enums
import tt.apps.common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_token_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="token_type",
            field=tt.apps.common.model_fields.LabeledEnumField(
                default="standard",
                enum_class=tt.apps.api.enums.TokenType,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Token Type",
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="api_token_hash",
            field=models.CharField(
                help_text="SHA256 hash of full api_token string", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="lookup_key",
            field=models.CharField(
                db_index=True,
                help_text="Random key for DB lookup (independent of secret_key)",
                max_length=8,
            ),
        ),
    ]
