# Generated by Django 5.2.7 on 2025-12-09 02:22

import django.db.models.deletion
import tt.apps.api.enums
import tt.apps.common.model_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_token_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncDeletionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True)),
                (
                    "object_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="location",
                        enum_class=tt.apps.api.enums.SyncObjectType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Object Type",
                    ),
                ),
                ("trip_uuid", models.UUIDField(db_index=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trip_uuid", "deleted_at"],
                        name="api_syncdel_trip_uu_97fbd9_idx",
                    )
                ],
            },
        ),
    ]
