# Generated by Django 5.2.7 on 2025-10-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subsystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "subsystem_key",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Subsystem Key"
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Subsystem",
                "verbose_name_plural": "Subsystems",
            },
        ),
        migrations.CreateModel(
            name="SubsystemAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "file_value",
                    models.FileField(blank=True, null=True, upload_to="attributes/"),
                ),
                (
                    "file_mime_type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Mime Type"
                    ),
                ),
                (
                    "value_type_str",
                    models.CharField(max_length=32, verbose_name="Value Type"),
                ),
                (
                    "value_range_str",
                    models.TextField(blank=True, null=True, verbose_name="Value Range"),
                ),
                (
                    "attribute_type_str",
                    models.CharField(max_length=32, verbose_name="Attribute Type"),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "setting_key",
                    models.CharField(max_length=255, verbose_name="Setting Key"),
                ),
                (
                    "subsystem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="config.subsystem",
                        verbose_name="Subsystem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsystem Attribute",
                "verbose_name_plural": "Subsystem Attributes",
            },
        ),
        migrations.CreateModel(
            name="SubsystemAttributeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "changed_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Changed"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="config.subsystemattribute",
                        verbose_name="Subsystem Attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsystem Attribute History",
                "verbose_name_plural": "Subsystem Attribute History",
            },
        ),
        migrations.AddConstraint(
            model_name="subsystemattribute",
            constraint=models.UniqueConstraint(
                fields=("user", "setting_key"), name="subsystemattribute_user_key"
            ),
        ),
        migrations.AddIndex(
            model_name="subsystemattributehistory",
            index=models.Index(
                fields=["attribute", "-changed_datetime"],
                name="config_subs_attribu_2cbd30_idx",
            ),
        ),
    ]
