"""
Django settings for Trip Tools project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from tt.environment.server import EnvironmentSettings

ENV = EnvironmentSettings.get()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = ENV.SECRET_KEY

DJANGO_SUPERUSER_EMAIL = ENV.DJANGO_SUPERUSER_EMAIL
DJANGO_SUPERUSER_PASSWORD = ENV.DJANGO_SUPERUSER_PASSWORD

SITE_ID = ENV.SITE_ID
SITE_DOMAIN = ENV.SITE_DOMAIN
SITE_NAME = ENV.SITE_NAME

ALLOWED_HOSTS = ENV.ALLOWED_HOSTS

CORS_ALLOWED_ORIGINS = ENV.CORS_ALLOWED_ORIGINS

CSP_DEFAULT_SRC = (
    "'self'",
    'data:',
) + ENV.EXTRA_CSP_URLS

CSP_CONNECT_SRC = (
    "'self'",
) + ENV.EXTRA_CSP_URLS

CSP_FRAME_SRC = (
    "'self'",
) + ENV.EXTRA_CSP_URLS

CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
) + ENV.EXTRA_CSP_URLS

CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
) + ENV.EXTRA_CSP_URLS

CSP_MEDIA_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    'data:',
) + ENV.EXTRA_CSP_URLS

CSP_IMG_SRC = (
    "'self'",
    'data:',
) + ENV.EXTRA_CSP_URLS

CSP_CHILD_SRC = (
    "'self'",
) + ENV.EXTRA_CSP_URLS

CSP_FONT_SRC = (
    "'self'",
    'data:',
) + ENV.EXTRA_CSP_URLS

CSP_WORKER_SRC = (
    "'self'",
) + ENV.EXTRA_CSP_URLS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipeline',
    'django.contrib.humanize',
    'anymail',
    'constance',
    'custom',
    'tt.environment',
    'tt.apps.common',
    'tt.apps.attribute',
    'tt.apps.user',
    'tt.apps.config',
    'tt.apps.console',
    'tt.apps.notify',

    'tt.apps.geo',
    'tt.apps.routes',
    'tt.apps.contacts',
    'tt.apps.trips',
    'tt.apps.members',
    'tt.apps.dashboard',
    'tt.apps.locations',
    'tt.apps.candidates',
    'tt.apps.planning',
    'tt.apps.itineraries',
    'tt.apps.bookings',
    'tt.apps.images',
    'tt.apps.journal',
    'tt.apps.travelog',
    'tt.apps.reviews',
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'tt.middleware.ExceptionMiddleware',
    'tt.middleware.ViewMiddleware',
    'tt.apps.user.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'tt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, "templates") ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'tt.environment.context_processors.client_config',
                'tt.environment.context_processors.shared_constants',
                'tt.apps.config.context_processors.settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'tt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': ENV.DATABASE_HOST,
        'PORT': ENV.DATABASE_PORT,
        'NAME': ENV.DATABASE_NAME,
        'USER': ENV.DATABASE_USER,
        'PASSWORD': ENV.DATABASE_PASSWORD,
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = ENV.MEDIA_ROOT
MEDIA_URL = '/media/'

PIPELINE = {
    'DISABLE_WRAPPER': True,  # Important since some scripts assume global scope

    'CSS_COMPRESSOR': None,  # Removed django-pipeline-csscompressor (unmaintained since 2016)
    'JS_COMPRESSOR': None,
    
    'STYLESHEETS': {
        'css_head': {
            'source_filenames': (
                'bootstrap/css/bootstrap.css',
                'css/main.css',
                'css/icons.css',
                'css/attribute.css',
                'css/trip_images.css',
            ),
            'output_filename': 'css/css_head.css',
        },
        'journal': {
            'source_filenames': (
                'css/journal.css',
            ),
            'output_filename': 'css/journal.css',
        },
        'journal_editor': {
            'source_filenames': (
                'css/journal.css',
                'css/journal-editor.css',
            ),
            'output_filename': 'css/journal_editor.css',
        },
        'travelog_css_head': {
            'source_filenames': (
                'bootstrap/css/bootstrap.css',
                'css/travelog.css',
                'css/journal.css',
            ),
            'output_filename': 'css/travelog_css_head.css',
        },
    },
    'JAVASCRIPT': {
        'js_before_content': {
            'source_filenames': (
                'js/jquery-3.7.0.min.js',
                'js/cookie.js',
                'js/antinode.js',
                'js/autosize.min.js',
                'js/main.js',
                'js/attr.js',
                'js/attr-dirty-tracking.js',
                'js/trip_images.js',
            ),
            'output_filename': 'js/js_before_content.js',
        },
        'js_after_content': {
            'source_filenames': (
                'js/popper.min.js',
                'bootstrap/js/bootstrap.js',
            ),
            'output_filename': 'js/js_after_content.js',
        },
        'journal': {
            'source_filenames': (
                'js/journal.js',
            ),
            'output_filename': 'js/journal.js',
        },
        'journal_editor': {
            'source_filenames': (
                'js/journal-editor.js',
            ),
            'output_filename': 'js/journal_editor.js',
        },
        'travelog_js_top': {
            'source_filenames': (
                'js/jquery-3.7.0.min.js',
                'js/cookie.js',
                'js/journal.js',
            ),
            'output_filename': 'js/travelog_js_top.js',
        },
        'travelog_js_bottom': {
            'source_filenames': (
                'js/popper.min.js',
                'bootstrap/js/bootstrap.js',
            ),
            'output_filename': 'js/travelog_js_bottom.js',
        },
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # in seconds
AUTO_LOGOUT = 60 * 24 * 365 * 100  # in minutes

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'
CONSTANCE_DATABASE_PREFIX = 'constance:tt:'

CONSTANCE_CONFIG = {
    'DOWN_FOR_MAINTENANCE': ( False, 'Should we force the down for maintenance page to show?' ),
}

REDIS_HOST = ENV.REDIS_HOST
REDIS_PORT = ENV.REDIS_PORT
REDIS_KEY_PREFIX = ENV.REDIS_KEY_PREFIX

CACHES = {
    'default': {
        # 'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': [
            f'redis://{REDIS_HOST}:{REDIS_PORT}',
        ],
        "KEY_PREFIX": f'main:{REDIS_KEY_PREFIX}',
    }
}


AUTH_USER_MODEL = "custom.CustomUser"

# ====================
# Transactional Emails

EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'

EMAIL_API_KEY = ENV.EMAIL_API_KEY
ANYMAIL = {
    'RESEND_API_KEY': EMAIL_API_KEY,
}

EMAIL_SUBJECT_PREFIX = "%s " % ENV.EMAIL_SUBJECT_PREFIX
DEFAULT_FROM_EMAIL = ENV.DEFAULT_FROM_EMAIL
SERVER_EMAIL = ENV.SERVER_EMAIL
FROM_EMAIL_NAME = "Trip Tools"

# Normal Settings
EMAIL_HOST = ENV.EMAIL_HOST
try:
    EMAIL_PORT = ENV.EMAIL_PORT
except (TypeError, ValueError):
    EMAIL_PORT = 587
    
EMAIL_HOST_USER = ENV.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = ENV.EMAIL_HOST_PASSWORD
EMAIL_TIMEOUT = 10  # In seconds

EMAIL_USE_TLS = ENV.EMAIL_USE_TLS
EMAIL_USE_SSL = ENV.EMAIL_USE_SSL
    
# Needed when sending emails in background tasks since HttpRequest not
# available. Override this for development/testing/staging.
#
BASE_URL_FOR_EMAIL_LINKS = f'http://{SITE_DOMAIN}'


# ====================
# Development-related Settings
# (override in development.py, not here)

# When tests functionality requires knowing if in unit test context.
UNIT_TESTING = False

# In development and debugging, the debug noise and interference from the
# background periodic monitoring tasks can be a problem. This gives a way
# to turn them off with one setting.
#
SUPPRESS_MONITORS = False

# ====================
# Development Testing Injection Points
# (enabled/disabled in environment-specific settings)

# For testing UI error display of the various attribute editing form errors.
DEBUG_INJECT_ATTRIBUTE_FORM_ERRORS = False
