blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/cassandra/home-information/discussions
    about: Use GitHub Discussions for general help or feature requests.
