# Generated by Django 5.2.7 on 2025-10-27 23:32

import django.db.models.deletion
import tt.apps.common.model_fields
import tt.apps.contacts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "contact_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("address", "Address"),
                            ("other", "Other"),
                        ],
                        default="phone",
                        enum_class=tt.apps.contacts.enums.ContactType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Phone number, email address, URL, physical address, or username"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='E.g., "Reservations", "Front Desk", "Customer Service"',
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context about this contact"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Mark as primary contact for this type"
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
                "ordering": ["-is_primary", "contact_type", "created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="contacts_co_content_b86e5c_idx",
                    ),
                    models.Index(
                        fields=["contact_type"], name="contacts_co_contact_4e7aba_idx"
                    ),
                ],
            },
        ),
    ]
