# Generated by Django 5.2.7 on 2025-11-20 18:27

import django.db.models.deletion
import tt.apps.common.model_fields
import tt.apps.journal.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("notebook", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for journal entries (pytz timezone name)",
                        max_length=63,
                    ),
                ),
                (
                    "visibility",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="private",
                        enum_class=tt.apps.journal.enums.JournalVisibility,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "_password",
                    models.CharField(
                        blank=True,
                        db_column="password",
                        help_text="Hashed password for PROTECTED visibility mode",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField()),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for this entry (pytz timezone name)",
                        max_length=63,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="HTML formatted journal entry text (sanitized on save)",
                    ),
                ),
                (
                    "source_notebook_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Version of source notebook entry when last synced",
                        null=True,
                    ),
                ),
                ("edit_version", models.IntegerField(default=1, editable=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="journal.journal",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries_as_reference",
                        to="images.tripimage",
                    ),
                ),
                (
                    "source_notebook_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="notebook.notebookentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ["date"],
                "unique_together": {("journal", "date")},
            },
        ),
    ]
