# Generated by Django 5.2.7 on 2025-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="HTML formatted journal entry text (sanitized on save)",
            ),
        ),
    ]
