# Generated by Django 5.2.7 on 2025-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journal_reference_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="include_in_publish",
            field=models.BooleanField(
                default=True,
                help_text="Include this entry when publishing journal to travelog",
            ),
        ),
    ]
