# Generated by Django 5.2.7 on 2025-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journalentry_reference_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="password_version",
            field=models.IntegerField(
                default=1,
                help_text="Version number incremented on each password change for session invalidation",
            ),
        ),
    ]
