# Generated by Django 5.2.7 on 2025-11-23 00:12

import tt.apps.common.model_fields
import tt.apps.journal.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_journal_password_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="theme",
            field=tt.apps.common.model_fields.LabeledEnumField(
                default="current",
                enum_class=tt.apps.journal.enums.JournalTheme,
                help_text="Visual color theme for published travelog pages",
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Travelog Theme",
            ),
        ),
    ]
