# Generated by Django 5.2.7 on 2025-11-23 14:56

import django.db.models.deletion
import tt.apps.common.model_fields
import tt.apps.journal.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journal", "0004_journal_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="reference_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entries",
                to="images.tripimage",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="theme",
            field=tt.apps.common.model_fields.LabeledEnumField(
                default="default",
                enum_class=tt.apps.journal.enums.JournalTheme,
                help_text="Visual color theme for published travelog pages",
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Travelog Theme",
            ),
        ),
    ]
