# Generated by Django 5.2.7 on 2025-10-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationcategory",
            name="color_code",
            field=models.CharField(
                blank=True,
                help_text='RGB color code, e.g., "RGB (245, 124, 0)"',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="locationcategory",
            name="icon_code",
            field=models.CharField(
                blank=True,
                help_text='Google Maps icon code, e.g., "1535"',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="locationsubcategory",
            name="color_code",
            field=models.CharField(
                blank=True,
                help_text='RGB color code, e.g., "RGB (9, 113, 56)"',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="locationsubcategory",
            name="icon_code",
            field=models.CharField(
                blank=True,
                help_text='Google Maps icon code, e.g., "1596"',
                max_length=20,
            ),
        ),
    ]
