# Generated by Django 5.2.7 on 2025-10-27 23:45

from django.db import migrations


def seed_location_categories(apps, schema_editor):
    """
    Seed LocationCategory and LocationSubCategory with initial data
    from tools/chrome/scripts/models.js and tools/chrome/scripts/mymap.js
    """
    LocationCategory = apps.get_model('locations', 'LocationCategory')
    LocationSubCategory = apps.get_model('locations', 'LocationSubCategory')

    # Create Categories
    categories_data = [
        {
            'name': 'Attractions',
            'slug': 'attractions',
            'color_code': 'RGB (245, 124, 0)',
            'icon_code': '1535',
            'subcategories': [
                {'name': 'Hike/Trail', 'slug': 'hike', 'color_code': 'RGB (9, 113, 56)', 'icon_code': '1596'},
                {'name': 'Museum', 'slug': 'museum', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1636'},
                {'name': 'Viewpoint/Photo Op', 'slug': 'view_photoop', 'color_code': 'RGB (57, 73, 171)', 'icon_code': '1535'},
                {'name': 'Neighborhood/Area', 'slug': 'neighborhood', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1604'},
                {'name': 'Town', 'slug': 'town', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1547'},
                {'name': 'Church/Religious', 'slug': 'church_religious', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1671'},
                {'name': 'Cemetery', 'slug': 'cemetery', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1542'},
                {'name': 'Store/Shop', 'slug': 'store_shop', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1686'},
                {'name': 'Historic/Ruins', 'slug': 'historic_ruins', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1598'},
                {'name': 'Park/Garden', 'slug': 'park_garden', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1582'},
                {'name': 'Waterfall', 'slug': 'waterfall', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1892'},
                {'name': 'Beach', 'slug': 'beach', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1521'},
                {'name': 'Cinema/Play', 'slug': 'cinema_play', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1635'},
                {'name': 'Monument', 'slug': 'monument', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1599'},
                {'name': 'Fountain/Statue', 'slug': 'fountain', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1580'},
                {'name': 'Artwork', 'slug': 'artwork', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1509'},
                {'name': 'Astronomy', 'slug': 'astronomy', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1878'},
                {'name': 'Cave', 'slug': 'cave', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1767'},
                {'name': 'Geothermal/Hot Springs', 'slug': 'geothermal', 'color_code': 'RGB (245, 124, 0)', 'icon_code': '1811'},
            ]
        },
        {
            'name': 'Dining',
            'slug': 'dining',
            'color_code': 'RGB (251, 192, 45)',
            'icon_code': '1577',
            'subcategories': [
                {'name': 'Lunch/Dinner', 'slug': 'lunch_dinner', 'color_code': 'RGB (251, 192, 45)', 'icon_code': '1577'},
                {'name': 'Coffee/Breakfast', 'slug': 'coffee_breakfast', 'color_code': 'RGB (121, 85, 72)', 'icon_code': '1534'},
                {'name': 'Deserts/Snacks', 'slug': 'deserts', 'color_code': 'RGB (57, 73, 171)', 'icon_code': '1607'},
                {'name': 'Drinks/Bar', 'slug': 'drinks_bar', 'color_code': 'RGB (156, 39, 176)', 'icon_code': '1517'},
                {'name': 'Food Area', 'slug': 'food_area', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1611'},
            ]
        },
        {
            'name': 'Towns',
            'slug': 'towns',
            'color_code': 'RGB (165, 39, 20)',
            'icon_code': '1603',
            'subcategories': []
        },
        {
            'name': 'Lodging',
            'slug': 'lodging',
            'color_code': 'RGB (194, 24, 91)',
            'icon_code': '1602',
            'subcategories': []
        },
        {
            'name': 'Transportation/Tours',
            'slug': 'transportation_tours',
            'color_code': 'RGB (0, 151, 167)',
            'icon_code': '1522',
            'subcategories': [
                {'name': 'Plane', 'slug': 'plane', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1504'},
                {'name': 'Car/Auto', 'slug': 'car_auto', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1538'},
                {'name': 'Boat', 'slug': 'boat', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1681'},
                {'name': 'Train', 'slug': 'train', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1716'},
                {'name': 'Cable Car/Funicular', 'slug': 'cable_car_funicular', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1533'},
                {'name': 'Walking', 'slug': 'walking', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1596'},
                {'name': 'Ferry', 'slug': 'ferry', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1569'},
                {'name': 'Bus', 'slug': 'bus', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1532'},
                {'name': 'Bicycle', 'slug': 'bicycle', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1522'},
                {'name': 'Helicopter', 'slug': 'helicopter', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1593'},
                {'name': 'Parking', 'slug': 'parking', 'color_code': 'RGB (0, 151, 167)', 'icon_code': '1644'},
            ]
        },
    ]

    # Create categories and subcategories
    for cat_data in categories_data:
        subcategories_data = cat_data.pop('subcategories')
        category = LocationCategory.objects.create(**cat_data)

        for subcat_data in subcategories_data:
            LocationSubCategory.objects.create(
                category=category,
                **subcat_data
            )


def reverse_seed(apps, schema_editor):
    """Remove seeded data"""
    LocationCategory = apps.get_model('locations', 'LocationCategory')
    LocationSubCategory = apps.get_model('locations', 'LocationSubCategory')

    # Delete all subcategories and categories
    LocationSubCategory.objects.all().delete()
    LocationCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_locationcategory_color_code_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_location_categories, reverse_seed),
    ]
