# Generated by Django 5.2.7 on 2025-12-04 21:46

import uuid
from django.db import migrations, models


def populate_uuids(apps, schema_editor):
    """Generate UUIDs for existing Location rows."""
    Location = apps.get_model('locations', 'Location')
    for location in Location.objects.all():
        location.uuid = uuid.uuid4()
        location.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_seed_location_categories"),
    ]

    operations = [
        # Step 1: Add nullable uuid field without unique constraint
        migrations.AddField(
            model_name="location",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate UUIDs for existing rows
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        # Step 3: Make field non-nullable and unique
        migrations.AlterField(
            model_name="location",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
