# Generated by Django 5.2.7 on 2025-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_seed_location_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="open_days_times",
            field=models.TextField(blank=True),
        ),
    ]
