# Generated by Django 5.2.7 on 2025-12-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_location_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
