# Generated by Django 5.2.7 on 2025-12-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_add_version_field"),
        ("routes", "0001_initial"),
        ("trips", "0003_add_version_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["trip", "modified_datetime"],
                name="locations_l_trip_id_808d3d_idx",
            ),
        ),
    ]
