# Generated by Django 5.2.7 on 2025-12-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_add_sync_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="gmm_id",
            field=models.CharField(
                blank=True,
                help_text="Google My Maps feature ID for extension sync",
                max_length=255,
                null=True,
            ),
        ),
    ]
