# Generated by Django 5.2.7 on 2025-12-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_add_gmm_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationnote",
            options={
                "ordering": ["sort_order", "created_datetime"],
                "verbose_name": "Location Note",
                "verbose_name_plural": "Location Notes",
            },
        ),
        migrations.AddField(
            model_name="locationnote",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
