# Generated by Django 5.2.7 on 2025-12-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_add_sort_order_to_location_note"),
        ("routes", "0001_initial"),
        ("trips", "0005_gmm_map_id_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gmm_id__isnull", False)),
                fields=("trip", "gmm_id"),
                name="unique_trip_gmm_id",
            ),
        ),
    ]
