# Generated by Django 5.2.7 on 2025-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_add_unique_trip_gmm_id_constraint"),
        ("routes", "0001_initial"),
        ("trips", "0005_gmm_map_id_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_trip_gmm_id",
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("trip", "gmm_id"), name="unique_trip_gmm_id"
            ),
        ),
    ]
