# Generated by Django 5.2.7 on 2025-11-06 02:06

import django.db.models.deletion
import tt.apps.images.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "web_image",
                    models.ImageField(
                        help_text="Web-sized image (max 1600px), saved via ContentFile",
                        max_length=255,
                        upload_to=tt.apps.images.models.trip_web_image_upload_path,
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (max 350px), saved via ContentFile",
                        max_length=255,
                        upload_to=tt.apps.images.models.trip_thumbnail_image_upload_path,
                    ),
                ),
                (
                    "datetime_utc",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags extracted from EXIF or user-added",
                    ),
                ),
                ("uploaded_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Image",
                "verbose_name_plural": "Trip Images",
                "ordering": ["-datetime_utc", "-uploaded_datetime"],
            },
        ),
    ]
