# Generated by Django 5.2.7 on 2025-11-23 18:30

import django.db.models.deletion
import tt.apps.images.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "web_image",
                    models.ImageField(
                        help_text="Web-sized image (max 1600px), saved via ContentFile",
                        max_length=255,
                        upload_to=tt.apps.images.models.trip_web_image_upload_path,
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (max 350px), saved via ContentFile",
                        max_length=255,
                        upload_to=tt.apps.images.models.trip_thumbnail_image_upload_path,
                    ),
                ),
                (
                    "datetime_utc",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags extracted from EXIF or user-added",
                    ),
                ),
                (
                    "has_exif",
                    models.BooleanField(
                        default=False,
                        help_text="Whether EXIF metadata was successfully extracted from the uploaded image",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="IANA timezone name if detected from EXIF data (e.g., 'America/New_York')",
                        max_length=63,
                        null=True,
                    ),
                ),
                ("uploaded_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last modification timestamp (auto-updated)",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this image metadata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
