# Generated by Django 5.2.7 on 2025-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripimage",
            name="upload_session_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Groups images from the same bulk upload batch for chronological ordering",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tripimage",
            name="uploaded_datetime",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
