# Generated by Django 5.2.7 on 2025-11-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripimage",
            name="has_exif",
            field=models.BooleanField(
                default=False,
                help_text="Whether EXIF metadata was successfully extracted from the uploaded image",
            ),
        ),
    ]
