# Generated by Django 5.2.7 on 2025-11-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_tripimage_has_exif"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripimage",
            name="timezone_unknown",
            field=models.BooleanField(
                default=False,
                help_text="Whether datetime_utc timezone is uncertain (no EXIF offset found, assumed UTC)",
            ),
        ),
    ]
