# Generated by Django 5.2.7 on 2025-11-19 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_tripimage_timezone_unknown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tripimage",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this image metadata",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tripimage",
            name="modified_datetime",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp (auto-updated)"
            ),
        ),
    ]
