# Generated by Django 5.2.7 on 2025-11-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_add_tripimage_edit_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tripimage",
            options={},
        ),
        migrations.RemoveField(
            model_name="tripimage",
            name="timezone_unknown",
        ),
        migrations.AddField(
            model_name="tripimage",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="IANA timezone name if detected from EXIF data (e.g., 'America/New_York')",
                max_length=63,
                null=True,
            ),
        ),
    ]
