# Generated by Django 5.2.7 on 2025-11-23 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Travelog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version_number", models.IntegerField()),
                ("is_current", models.BooleanField(default=False)),
                ("published_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travelogs",
                        to="journal.journal",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_travelogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_entries",
                        to="images.tripimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travelog",
                "verbose_name_plural": "Travelogs",
                "ordering": ["-version_number"],
                "unique_together": {("journal", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="TravelogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField()),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for this entry (pytz timezone name)",
                        max_length=63,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="HTML formatted journal entry text (sanitized on save)",
                    ),
                ),
                (
                    "reference_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_entries",
                        to="images.tripimage",
                    ),
                ),
                (
                    "source_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travelog_snapshots",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "travelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="travelog.travelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travelog Entry",
                "verbose_name_plural": "Travelog Entries",
                "ordering": ["date"],
            },
        ),
    ]
