# Generated by Django 5.2.7 on 2025-11-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("travelog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelog",
            name="reference_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_references",
                to="images.tripimage",
            ),
        ),
        migrations.AlterField(
            model_name="travelogentry",
            name="reference_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_references",
                to="images.tripimage",
            ),
        ),
    ]
