from django.urls import path

from . import views

urlpatterns = [
    path(
        'trip/<uuid:trip_uuid>',
        views.JournalAllView.as_view(),
        name='journal_all'
    ),
    path(
        'trip/<uuid:trip_uuid>/create',
        views.JournalCreateView.as_view(),
        name='journal_create'
    ),
    path(
        '<uuid:journal_uuid>',
        views.JournalHomeView.as_view(),
        name='journal_home'
    ),
    path(
        '<uuid:journal_uuid>/edit',
        views.JournalEditView.as_view(),
        name='journal_edit'
    ),
    path(
        '<uuid:journal_uuid>/visibility',
        views.JournalVisibilityChangeView.as_view(),
        name='journal_visibility'
    ),
    path(
        '<uuid:journal_uuid>/publish',
        views.JournalPublishModalView.as_view(),
        name='journal_publish'
    ),
    path(
        '<uuid:journal_uuid>/versions',
        views.JournalVersionHistoryView.as_view(),
        name='journal_versions'
    ),
    path(
        '<uuid:journal_uuid>/set-current/<uuid:travelog_uuid>',
        views.JournalSetCurrentVersionView.as_view(),
        name='journal_set_current'
    ),
    path(
        '<uuid:journal_uuid>/restore/<uuid:travelog_uuid>',
        views.JournalRestoreView.as_view(),
        name='journal_restore'
    ),
    path(
        '<uuid:journal_uuid>/reference-image-picker/',
        views.JournalReferenceImagePickerView.as_view(),
        name='journal_reference_image_picker'
    ),
    path(
        '<uuid:journal_uuid>/upload-image/',
        views.JournalImageUploadView.as_view(),
        name='journal_image_upload'
    ),
    path(
        '<uuid:journal_uuid>/entry/new/',
        views.JournalEntryNewView.as_view(),
        name='journal_entry_new'
    ),
    path(
        '<uuid:journal_uuid>/entry/prologue/new/',
        views.JournalPrologueNewView.as_view(),
        name='journal_prologue_new'
    ),
    path(
        '<uuid:journal_uuid>/entry/epilogue/new/',
        views.JournalEpilogueNewView.as_view(),
        name='journal_epilogue_new'
    ),
    path(
        'entry/<uuid:entry_uuid>',
        views.JournalEntryView.as_view(),
        name='journal_entry'
    ),
    path(
        'entry/<uuid:entry_uuid>/save',
        views.JournalEntryAutosaveView.as_view(),
        name='journal_entry_autosave'
    ),
    path(
        'entry/<uuid:entry_uuid>/delete',
        views.JournalEntryDeleteModalView.as_view(),
        name='journal_entry_delete'
    ),
    path(
        'entry/<uuid:entry_uuid>/editor-images/',
        views.JournalEditorMultiImagePickerView.as_view(),
        name='journal_editor_multi_images'
    ),
    path(
        'entry/<uuid:entry_uuid>/reference-image-picker/',
        views.JournalEntryImagePickerView.as_view(),
        name='journal_entry_reference_image_picker'
    ),
    path(
        'entry/<uuid:entry_uuid>/upload-image/',
        views.JournalEntryImageUploadView.as_view(),
        name='journal_entry_image_upload'
    ),
    path(
        'entry/<uuid:entry_uuid>/editor-images-upload/',
        views.JournalEditorMultiImageUploadView.as_view(),
        name='journal_editor_multi_image_upload'
    ),
    path(
        'entry/editor-help',
        views.JournalEditorHelpView.as_view(),
        name='journal_editor_help'
    ),
]
