name: Django Tests

on:
  pull_request:
    branches: [master, staging]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7  # Use the latest Redis version
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    env:
      DJANGO_SETTINGS_MODULE: "tt.settings.ci"
      DJANGO_SECRET_KEY: "django-insecure-@egpl51khoap^%x8*jc4xj0(hv)foor-%5897+@h665k3txo))7"
      DJANGO_SUPERUSER_EMAIL: "foo@example.com"
      DJANGO_SUPERUSER_PASSWORD: "foobar"
      TT_REDIS_HOST: "localhost"
      TT_REDIS_PORT: "6379"
      TT_DB_PATH: "/tmp"
      TT_MEDIA_PATH: "/tmp"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/tt/requirements/development.txt

      - name: Run Unit Tests
        working-directory: ./src
        run: |
          python manage.py test

      - name: Check Code Style
        working-directory: ./src
        run: |
          flake8 . --config=.flake8-ci
