# Generated by Django 5.2.7 on 2025-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookentry",
            name="edit_version",
            field=models.IntegerField(default=1),
        ),
    ]
