# Generated by Django 5.2.7 on 2025-11-20 18:27

import django.db.models.deletion
import tt.apps.attribute.enums
import tt.apps.candidates.enums
import tt.apps.common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("routes", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., hotel name, airline + flight number, tour operator",
                        max_length=200,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, help_text="E.g., USD, EUR, GBP", max_length=3
                    ),
                ),
                ("preference_order", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this option"
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="locations.location",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "preference_order"],
            },
        ),
        migrations.CreateModel(
            name="CandidateAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "file_value",
                    models.FileField(blank=True, null=True, upload_to="attributes/"),
                ),
                (
                    "file_mime_type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Mime Type"
                    ),
                ),
                (
                    "value_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="text",
                        enum_class=tt.apps.attribute.enums.AttributeValueType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "value_range_str",
                    models.TextField(blank=True, null=True, verbose_name="Value Range"),
                ),
                (
                    "attribute_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="predefined",
                        enum_class=tt.apps.attribute.enums.AttributeType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Attribute Type",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Attribute",
                "verbose_name_plural": "Candidate Attributes",
            },
        ),
        migrations.CreateModel(
            name="CandidateGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_type",
                    tt.apps.common.model_fields.LabeledEnumField(
                        default="transportation",
                        enum_class=tt.apps.candidates.enums.CandidateType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Candidate Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='E.g., "Hotels near Louvre", "Flights Paris to Rome", "Cooking classes"',
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Context about what you're looking for"
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_groups",
                        to="locations.location",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_groups",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Group",
                "verbose_name_plural": "Candidate Groups",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="candidates.candidategroup",
            ),
        ),
    ]
